config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-ultramarine-terrier.sh
        container: qc.acc_cranky-pink-rabbit
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-amethyst-bombay.sh
        container: qc.doc_jumpy-cinnamon-stoat
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-dandelion-capuchin.sh
        container: qc.doc_pokey-magenta-stoat
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-firebrick-squirrel.sh
        container: qc.doc_scummy-ultramarine-paradise
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-green-mouse.sh
        container: qc.lic_gimpy-flax-mongoose
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-fuchsia-sparrow.sh
        container: qc.met_flaky-apricot-woodlouse
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-turquoise-echidna.sh
        container: qc.sec_muggy-amber-walrus
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-chocolate-monkey.sh
        container: qc.sty_lumpy-gamboge-pig
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-eggplant-lion.sh
        container: qc.sty_crappy-auburn-bobcat
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-saffron-reindeer.sh
        container: qc.sty_geeky-olive-capuchin
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-beige-chinook.sh
        container: qc.ver_leaky-goldenrod-barnacle
timeout: 5400
