config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-corn-worm.sh
        container: qc.acc_messy-gamboge-hamster
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-crimson-russel.sh
        container: qc.doc_pasty-goldenrod-markhor
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-violet-dachshund.sh
        container: qc.doc_homey-turquoise-frigatebird
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-ruby-tamarin.sh
        container: qc.doc_tacky-amaranth-newt
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-tangerine-kangaroo.sh
        container: qc.lic_goopy-denim-whale
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-wheat-cuttlefish.sh
        container: qc.met_tasty-amber-heron
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-yellow-dodo.sh
        container: qc.sec_wiggy-auburn-turkey
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-buff-salamander.sh
        container: qc.sty_slimy-saffron-cichlid
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-pear-hyena.sh
        container: qc.sty_beady-blue-boar
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/nearline-ml-ai-engine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-cornflower-seahorse.sh
        container: qc.ver_muzzy-amethyst-javanese
timeout: 5400
